server {
    listen 8080;

    location /auth/ {
        proxy_pass http://127.0.0.1:8000/api/v1/;
    }

    location /backend/ {
      proxy_pass http://127.0.0.1:8001/backend/;
      proxy_buffering off;
      proxy_cache off;

      # 核心：设置超时时间（建议设长一些，如 1小时）
      proxy_read_timeout 3600s; 
      proxy_send_timeout 3600s;

      # 保持与后端的连接活跃
      keepalive_timeout 3600s;
    }
}
