# Generated by Django 6.0 on 2025-12-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
