# Generated by Django 6.0 on 2025-12-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_id', models.CharField(max_length=100, unique=True, verbose_name='模型标识')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='模型描述')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('alibaba', 'Alibaba'), ('siliconflow', 'SiliconFlow'), ('other', 'Other')], default='openai', max_length=50, verbose_name='供应商')),
                ('icon', models.CharField(choices=[('sparkles', 'Sparkles'), ('zap', 'Zap'), ('brain', 'Brain'), ('cpu', 'Cpu'), ('bot', 'Bot')], default='sparkles', max_length=20, verbose_name='图标')),
                ('icon_color', models.CharField(default='text-blue-500', max_length=20, verbose_name='图标颜色')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('api_base_url', models.URLField(blank=True, max_length=255, verbose_name='API Base URL')),
                ('api_key_env', models.CharField(blank=True, max_length=100, verbose_name='API Key 环境变量名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
