# Generated by Django 6.0 on 2025-12-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Key (直接填写)'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='api_key_env',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Key 环境变量名 (备选)'),
        ),
    ]
